steps:
  - name: node:14.10.0
    entrypoint: npm
    args: [ 'install' ]
  - name: node:14.10.0
    entrypoint: npm
    env:
      - 'CI=true'
    args: [ 'test' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest' ]